apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-01
spec:
  capacity:
    storage: 100Gi                # Dung lượng
  accessModes:
    - ReadWriteMany               # Nhiều Pod cùng đọc/ghi
  persistentVolumeReclaimPolicy: Retain  # Khi PVC xóa, PV vẫn giữ lại
  nfs:
    server: 10.10.10.100
    path: /k8s-data