#mặc định – chỉ truy cập nội bộ cluster
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: production
spec:
  type: ClusterIP                  # Mặc định nếu không ghi
  selector:
    app: nginx                     # Chọn Pod nào có label này
  ports:
    - protocol: TCP
      port: 80                     # Port mà Service expose ra
      targetPort: 80               # Port của Pod (có thể dùng tên nếu có named port)