#dùng trên cloud AWS/GCP/Azure
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer               # Cloud sẽ tạo public LB tự động
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80